### ISSUE TITLE
Fix LibGit2Sharp.Tests/GlobalSettingsFixture.cs

### ISSUE THREAD

**Issue by MarcellvanRooyen** [mendix/libgit2sharp#2]
we commented out the code here to fix the issue where NativeDllName reference would show an error if we import the incorrect package reference.

Fix the issue and re-include the test fixture

Update LibGit2Sharp.Tests/GlobalSettingsFixture.cs

**Comment by ghost** [comment]
@MarcellvanRooyen I've uncommented it in the new `mendix/releases` branch, let's see if it builds.
